name: tochegando_delivery_parceiros
description: Aplicativo To Chegando Delivery Parceiros
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Suporte a internacionalização e traduções
  flutter_localizations:
    sdk: flutter

  intl: ^0.20.2

  # Pacote atualizado do Syncfusion que suporta intl 0.20.x
  syncfusion_flutter_datepicker: ^31.1.17

  # Outras dependências do projeto
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  shared_preferences: ^2.3.2
  provider: ^6.1.2
  get: ^4.6.6
  firebase_core: ^3.6.0
  firebase_messaging: ^15.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true  # 👈 Corrige o erro do app_localizations

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
